name: sl
description: A structured logging library.
version: 0.0.5
repository: https://github.com/iv-re/dart-sl

environment:
  sdk: ^3.12.1

dependencies:
  ctx: ^0.0.3
  logging: ^1.2.0
  stack_trace: ^1.12.1

dev_dependencies:
  test: ^1.25.6
  mocktail: ^1.0.5
  pusk_lints: ^1.0.0
